# To run on all files use `pre-commit run --all-files`
#
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
# -   repo: https://github.com/pre-commit/pre-commit-hooks
#     rev: v2.4.0
#     hooks:
#     -   id: trailing-whitespace
#     -   id: end-of-file-fixer
#     -   id: check-yaml
#     -   id: check-added-large-files
# See https://github.com/ambv/black for black options
# See https://www.mattlayman.com/blog/2018/python-code-black/ for tutorial
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    -   id: black
        language_version: python3.7
